import type { Metadata } from "next";
import Theme from "./theme";
import 'dayjs/locale/pt';
import { DatesProvider } from '@mantine/dates';

export const metadata: Metadata = {
  title: "Ludonautas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <body>
        <DatesProvider settings={{ locale: 'pt' }}>
          <Theme>
            {children}
          </Theme>
        </DatesProvider>
      </body>
    </html>
  );
}
